//To describe usage of throws clause
class ThrowException {
public static void main(String args[])throws ArithmeticException{
	  System.out.println("inside main");
	  int i=0;
	  int j=40/i;
	  System.out.println("this statement is not printed");
	}
 }